// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: review.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteReview = `-- name: DeleteReview :execrows
DELETE FROM review.reviews WHERE id = $1
`

func (q *Queries) DeleteReview(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteReview, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserReviews = `-- name: DeleteUserReviews :execrows
DELETE FROM review.reviews WHERE user_id = $1
`

func (q *Queries) DeleteUserReviews(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserReviews, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getReviewByUser = `-- name: GetReviewByUser :one
SELECT id, product_id, user_id, rating, title, body, author, status, created_at, updated_at FROM review.reviews WHERE product_id = $1 AND user_id = $2
`

type GetReviewByUserParams struct {
	ProductID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) GetReviewByUser(ctx context.Context, arg GetReviewByUserParams) (ReviewReview, error) {
	row := q.db.QueryRow(ctx, getReviewByUser, arg.ProductID, arg.UserID)
	var i ReviewReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.Author,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllReviews = `-- name: ListAllReviews :many
SELECT id, product_id, user_id, rating, title, body, author, status, created_at, updated_at FROM review.reviews
WHERE ($1::text = '' OR status = $1::text)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListAllReviewsParams struct {
	Status     string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListAllReviews(ctx context.Context, arg ListAllReviewsParams) ([]ReviewReview, error) {
	rows, err := q.db.Query(ctx, listAllReviews, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewReview
	for rows.Next() {
		var i ReviewReview
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.Author,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedReviews = `-- name: ListPublishedReviews :many
SELECT id, product_id, user_id, rating, title, body, author, status, created_at, updated_at FROM review.reviews WHERE product_id = $1 AND status = 'published' ORDER BY created_at DESC, id DESC LIMIT $2
`

type ListPublishedReviewsParams struct {
	ProductID uuid.UUID
	Limit     int32
}

func (q *Queries) ListPublishedReviews(ctx context.Context, arg ListPublishedReviewsParams) ([]ReviewReview, error) {
	rows, err := q.db.Query(ctx, listPublishedReviews, arg.ProductID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewReview
	for rows.Next() {
		var i ReviewReview
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.Author,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserReviews = `-- name: ListUserReviews :many
SELECT id, product_id, user_id, rating, title, body, author, status, created_at, updated_at FROM review.reviews WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUserReviews(ctx context.Context, userID uuid.UUID) ([]ReviewReview, error) {
	rows, err := q.db.Query(ctx, listUserReviews, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewReview
	for rows.Next() {
		var i ReviewReview
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.Rating,
			&i.Title,
			&i.Body,
			&i.Author,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ratingDistribution = `-- name: RatingDistribution :many
SELECT rating::int AS stars, count(*)::bigint AS n FROM review.reviews WHERE product_id = $1 AND status = 'published' GROUP BY rating
`

type RatingDistributionRow struct {
	Stars int32
	N     int64
}

func (q *Queries) RatingDistribution(ctx context.Context, productID uuid.UUID) ([]RatingDistributionRow, error) {
	rows, err := q.db.Query(ctx, ratingDistribution, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RatingDistributionRow
	for rows.Next() {
		var i RatingDistributionRow
		if err := rows.Scan(&i.Stars, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ratingSummaries = `-- name: RatingSummaries :many
SELECT product_id, count(*)::bigint AS n, avg(rating)::float8 AS avg_rating
FROM review.reviews
WHERE product_id = ANY($1::uuid[]) AND status = 'published'
GROUP BY product_id
`

type RatingSummariesRow struct {
	ProductID uuid.UUID
	N         int64
	AvgRating float64
}

func (q *Queries) RatingSummaries(ctx context.Context, ids []uuid.UUID) ([]RatingSummariesRow, error) {
	rows, err := q.db.Query(ctx, ratingSummaries, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RatingSummariesRow
	for rows.Next() {
		var i RatingSummariesRow
		if err := rows.Scan(&i.ProductID, &i.N, &i.AvgRating); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setReviewStatus = `-- name: SetReviewStatus :execrows
UPDATE review.reviews SET status = $2, updated_at = now() WHERE id = $1
`

type SetReviewStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetReviewStatus(ctx context.Context, arg SetReviewStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setReviewStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertReview = `-- name: UpsertReview :one
INSERT INTO review.reviews (id, product_id, user_id, rating, title, body, author)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (product_id, user_id) DO UPDATE
    SET rating = EXCLUDED.rating, title = EXCLUDED.title, body = EXCLUDED.body, author = EXCLUDED.author, updated_at = now()
RETURNING id, product_id, user_id, rating, title, body, author, status, created_at, updated_at
`

type UpsertReviewParams struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	UserID    uuid.UUID
	Rating    int16
	Title     string
	Body      string
	Author    string
}

// One review per customer per product: writing again edits it (and re-publishes it unless staff hid it).
func (q *Queries) UpsertReview(ctx context.Context, arg UpsertReviewParams) (ReviewReview, error) {
	row := q.db.QueryRow(ctx, upsertReview,
		arg.ID,
		arg.ProductID,
		arg.UserID,
		arg.Rating,
		arg.Title,
		arg.Body,
		arg.Author,
	)
	var i ReviewReview
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.Rating,
		&i.Title,
		&i.Body,
		&i.Author,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
