// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const claimPaidOrders = `-- name: ClaimPaidOrders :many
SELECT id FROM orders.orders WHERE status = 'paid' ORDER BY created_at LIMIT $1 FOR UPDATE SKIP LOCKED
`

// Fulfillment workers each take a disjoint batch; SKIP LOCKED avoids contention.
func (q *Queries) ClaimPaidOrders(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, claimPaidOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countOrdersByStatus = `-- name: CountOrdersByStatus :many
SELECT status, count(*)::bigint AS n FROM orders.orders GROUP BY status
`

type CountOrdersByStatusRow struct {
	Status string
	N      int64
}

func (q *Queries) CountOrdersByStatus(ctx context.Context) ([]CountOrdersByStatusRow, error) {
	rows, err := q.db.Query(ctx, countOrdersByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOrdersByStatusRow
	for rows.Next() {
		var i CountOrdersByStatusRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
SELECT id, user_id, status, total_cents, currency, idempotency_key, shipping, payment_id, created_at, updated_at FROM orders.orders WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id uuid.UUID) (OrdersOrder, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i OrdersOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.IdempotencyKey,
		&i.Shipping,
		&i.PaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT id, user_id, status, total_cents, currency, idempotency_key, shipping, payment_id, created_at, updated_at FROM orders.orders WHERE user_id = $1 AND idempotency_key = $2
`

type GetOrderByIdempotencyKeyParams struct {
	UserID         uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, arg GetOrderByIdempotencyKeyParams) (OrdersOrder, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, arg.UserID, arg.IdempotencyKey)
	var i OrdersOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.IdempotencyKey,
		&i.Shipping,
		&i.PaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
SELECT id, user_id, status, total_cents, currency, idempotency_key, shipping, payment_id, created_at, updated_at FROM orders.orders WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetOrderForUpdate(ctx context.Context, id uuid.UUID) (OrdersOrder, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i OrdersOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.TotalCents,
		&i.Currency,
		&i.IdempotencyKey,
		&i.Shipping,
		&i.PaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO orders.orders (id, user_id, status, total_cents, currency, idempotency_key, shipping)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOrderParams struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	Status         string
	TotalCents     int64
	Currency       string
	IdempotencyKey string
	Shipping       []byte
}

func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.TotalCents,
		arg.Currency,
		arg.IdempotencyKey,
		arg.Shipping,
	)
	return err
}

const insertOrderItem = `-- name: InsertOrderItem :exec
INSERT INTO orders.order_items (order_id, product_id, name, unit_price_cents, quantity)
VALUES ($1, $2, $3, $4, $5)
`

type InsertOrderItemParams struct {
	OrderID        uuid.UUID
	ProductID      uuid.UUID
	Name           string
	UnitPriceCents int64
	Quantity       int32
}

func (q *Queries) InsertOrderItem(ctx context.Context, arg InsertOrderItemParams) error {
	_, err := q.db.Exec(ctx, insertOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Name,
		arg.UnitPriceCents,
		arg.Quantity,
	)
	return err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT order_id, product_id, name, unit_price_cents, quantity, variant_id, variant_label, sku FROM orders.order_items WHERE order_id = $1 ORDER BY name
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID uuid.UUID) ([]OrdersOrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrdersOrderItem
	for rows.Next() {
		var i OrdersOrderItem
		if err := rows.Scan(
			&i.OrderID,
			&i.ProductID,
			&i.Name,
			&i.UnitPriceCents,
			&i.Quantity,
			&i.VariantID,
			&i.VariantLabel,
			&i.Sku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, user_id, status, total_cents, currency, idempotency_key, shipping, payment_id, created_at, updated_at FROM orders.orders
WHERE ($1::text = '' OR status = $1::text)
ORDER BY created_at DESC, id DESC
LIMIT $3 OFFSET $2
`

type ListOrdersParams struct {
	Status     string
	PageOffset int32
	PageLimit  int32
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]OrdersOrder, error) {
	rows, err := q.db.Query(ctx, listOrders, arg.Status, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrdersOrder
	for rows.Next() {
		var i OrdersOrder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalCents,
			&i.Currency,
			&i.IdempotencyKey,
			&i.Shipping,
			&i.PaymentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT id, user_id, status, total_cents, currency, idempotency_key, shipping, payment_id, created_at, updated_at FROM orders.orders WHERE user_id = $1 ORDER BY created_at DESC, id DESC LIMIT $2
`

type ListOrdersByUserParams struct {
	UserID uuid.UUID
	Limit  int32
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]OrdersOrder, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrdersOrder
	for rows.Next() {
		var i OrdersOrder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.TotalCents,
			&i.Currency,
			&i.IdempotencyKey,
			&i.Shipping,
			&i.PaymentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOrderPayment = `-- name: SetOrderPayment :exec
UPDATE orders.orders SET payment_id = $2, updated_at = now() WHERE id = $1
`

type SetOrderPaymentParams struct {
	ID        uuid.UUID
	PaymentID *uuid.UUID
}

func (q *Queries) SetOrderPayment(ctx context.Context, arg SetOrderPaymentParams) error {
	_, err := q.db.Exec(ctx, setOrderPayment, arg.ID, arg.PaymentID)
	return err
}

const setOrderStatus = `-- name: SetOrderStatus :execrows
UPDATE orders.orders SET status = $2, updated_at = now() WHERE id = $1
`

type SetOrderStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOrderStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
