// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addCartItem = `-- name: AddCartItem :exec
INSERT INTO cart.cart_items (cart_id, variant_id, quantity) VALUES ($1, $2, $3)
ON CONFLICT (cart_id, variant_id) DO UPDATE SET quantity = LEAST(20, cart.cart_items.quantity + EXCLUDED.quantity)
`

type AddCartItemParams struct {
	CartID    uuid.UUID
	VariantID uuid.UUID
	Quantity  int32
}

func (q *Queries) AddCartItem(ctx context.Context, arg AddCartItemParams) error {
	_, err := q.db.Exec(ctx, addCartItem, arg.CartID, arg.VariantID, arg.Quantity)
	return err
}

const clearCart = `-- name: ClearCart :exec
DELETE FROM cart.cart_items WHERE cart_id = $1
`

func (q *Queries) ClearCart(ctx context.Context, cartID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const countCartItems = `-- name: CountCartItems :one
SELECT (COALESCE(sum(ci.quantity), 0))::bigint
FROM cart.cart_items ci JOIN cart.carts c ON c.id = ci.cart_id
WHERE c.owner = $1
`

func (q *Queries) CountCartItems(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countCartItems, owner)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteCartByOwner = `-- name: DeleteCartByOwner :exec
DELETE FROM cart.carts WHERE owner = $1
`

func (q *Queries) DeleteCartByOwner(ctx context.Context, owner string) error {
	_, err := q.db.Exec(ctx, deleteCartByOwner, owner)
	return err
}

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart.cart_items WHERE cart_id = $1 AND variant_id = $2
`

type DeleteCartItemParams struct {
	CartID    uuid.UUID
	VariantID uuid.UUID
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.CartID, arg.VariantID)
	return err
}

const getCartID = `-- name: GetCartID :one
SELECT id FROM cart.carts WHERE owner = $1
`

func (q *Queries) GetCartID(ctx context.Context, owner string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getCartID, owner)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT variant_id, quantity FROM cart.cart_items WHERE cart_id = $1 ORDER BY variant_id
`

type ListCartItemsRow struct {
	VariantID uuid.UUID
	Quantity  int32
}

func (q *Queries) ListCartItems(ctx context.Context, cartID uuid.UUID) ([]ListCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsRow
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(&i.VariantID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCartByOwner = `-- name: LockCartByOwner :one
SELECT id FROM cart.carts WHERE owner = $1 FOR UPDATE
`

// Serialises concurrent merges of the same guest cart.
func (q *Queries) LockCartByOwner(ctx context.Context, owner string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockCartByOwner, owner)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const mergeCartItems = `-- name: MergeCartItems :exec
INSERT INTO cart.cart_items (cart_id, variant_id, quantity)
SELECT $1::uuid, variant_id, quantity FROM cart.cart_items WHERE cart_id = $2::uuid
ON CONFLICT (cart_id, variant_id) DO UPDATE SET quantity = LEAST(20, cart.cart_items.quantity + EXCLUDED.quantity)
`

type MergeCartItemsParams struct {
	ToCart   uuid.UUID
	FromCart uuid.UUID
}

func (q *Queries) MergeCartItems(ctx context.Context, arg MergeCartItemsParams) error {
	_, err := q.db.Exec(ctx, mergeCartItems, arg.ToCart, arg.FromCart)
	return err
}

const purgeGuestCarts = `-- name: PurgeGuestCarts :execrows
DELETE FROM cart.carts WHERE owner LIKE 'guest:%' AND updated_at < $1
`

func (q *Queries) PurgeGuestCarts(ctx context.Context, updatedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeGuestCarts, updatedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCartItem = `-- name: SetCartItem :exec
INSERT INTO cart.cart_items (cart_id, variant_id, quantity) VALUES ($1, $2, $3)
ON CONFLICT (cart_id, variant_id) DO UPDATE SET quantity = EXCLUDED.quantity
`

type SetCartItemParams struct {
	CartID    uuid.UUID
	VariantID uuid.UUID
	Quantity  int32
}

func (q *Queries) SetCartItem(ctx context.Context, arg SetCartItemParams) error {
	_, err := q.db.Exec(ctx, setCartItem, arg.CartID, arg.VariantID, arg.Quantity)
	return err
}

const upsertCart = `-- name: UpsertCart :one
INSERT INTO cart.carts (id, owner) VALUES ($1, $2)
ON CONFLICT (owner) DO UPDATE SET updated_at = now()
RETURNING id
`

type UpsertCartParams struct {
	ID    uuid.UUID
	Owner string
}

func (q *Queries) UpsertCart(ctx context.Context, arg UpsertCartParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, upsertCart, arg.ID, arg.Owner)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
