// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payment.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getPayment = `-- name: GetPayment :one
SELECT id, order_id, user_id, amount_cents, currency, provider, provider_ref, status, created_at, updated_at FROM payment.payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id uuid.UUID) (PaymentPayment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i PaymentPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPayment = `-- name: InsertPayment :exec
INSERT INTO payment.payments (id, order_id, user_id, amount_cents, currency, provider)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPaymentParams struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	UserID      uuid.UUID
	AmountCents int64
	Currency    string
	Provider    string
}

func (q *Queries) InsertPayment(ctx context.Context, arg InsertPaymentParams) error {
	_, err := q.db.Exec(ctx, insertPayment,
		arg.ID,
		arg.OrderID,
		arg.UserID,
		arg.AmountCents,
		arg.Currency,
		arg.Provider,
	)
	return err
}

const settlePayment = `-- name: SettlePayment :one
UPDATE payment.payments
SET status = $1::text,
    provider_ref = CASE WHEN $2::text <> '' THEN $2::text ELSE provider_ref END,
    updated_at = now()
WHERE id = $3 AND status = 'pending'
RETURNING id, order_id, user_id, amount_cents, currency, provider, provider_ref, status, created_at, updated_at
`

type SettlePaymentParams struct {
	Status      string
	ProviderRef string
	ID          uuid.UUID
}

// Only a pending payment can settle, which makes webhook redelivery idempotent.
func (q *Queries) SettlePayment(ctx context.Context, arg SettlePaymentParams) (PaymentPayment, error) {
	row := q.db.QueryRow(ctx, settlePayment, arg.Status, arg.ProviderRef, arg.ID)
	var i PaymentPayment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.UserID,
		&i.AmountCents,
		&i.Currency,
		&i.Provider,
		&i.ProviderRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
