// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AlertsSent struct {
	Key    string
	SentAt time.Time
}

type CartCart struct {
	ID         uuid.UUID
	Owner      string
	UpdatedAt  time.Time
	RemindedAt *time.Time
}

type CartCartItem struct {
	CartID    uuid.UUID
	VariantID uuid.UUID
	Quantity  int32
}

type CatalogCategory struct {
	ID   uuid.UUID
	Slug string
	Name string
}

type CatalogProduct struct {
	ID          uuid.UUID
	CategoryID  *uuid.UUID
	Slug        string
	Name        string
	Description string
	PriceCents  int64
	Currency    string
	ImageUrl    string
	Active      bool
	CreatedAt   time.Time
	ArchivedAt  *time.Time
	OptionName  string
	ThumbUrl    string
}

type CatalogProductImage struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	Url       string
	ThumbUrl  string
	Alt       string
	Position  int32
	CreatedAt time.Time
}

type CatalogVariant struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	Sku        string
	Label      string
	PriceCents *int64
	Position   int32
	Active     bool
	CreatedAt  time.Time
}

type ContentPage struct {
	ID        uuid.UUID
	Slug      string
	Title     string
	Body      string
	Published bool
	Position  int32
	CreatedAt time.Time
	UpdatedAt time.Time
}

type IdentityActionToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	TokenHash []byte
	ExpiresAt time.Time
	UsedAt    *time.Time
	CreatedAt time.Time
}

type IdentityAddress struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	FullName   string
	Phone      string
	Line1      string
	Line2      string
	City       string
	PostalCode string
	Country    string
	IsDefault  bool
	CreatedAt  time.Time
}

type IdentityRefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
	RotatedAt *time.Time
}

type IdentityUser struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	Name            string
	Role            string
	CreatedAt       time.Time
	EmailVerifiedAt *time.Time
	Guest           bool
	DisabledAt      *time.Time
	CartReminders   bool
}

type InventoryReservation struct {
	ID        uuid.UUID
	OrderID   uuid.UUID
	VariantID uuid.UUID
	LotID     uuid.UUID
	Quantity  int32
	Status    string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type InventoryStockLot struct {
	ID        uuid.UUID
	VariantID uuid.UUID
	Label     string
	Quantity  int32
	CreatedAt time.Time
}

type OrdersOrder struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	Status            string
	TotalCents        int64
	Currency          string
	IdempotencyKey    string
	Shipping          []byte
	PaymentID         *uuid.UUID
	CreatedAt         time.Time
	UpdatedAt         time.Time
	SubtotalCents     int64
	DiscountCents     int64
	ShippingCents     int64
	TaxCents          int64
	TaxInclusive      bool
	ShippingMethod    string
	CouponCode        string
	PaymentMethod     string
	ContactEmail      string
	TrackingCarrier   string
	TrackingNumber    string
	TrackingUrl       string
	ShippedAt         *time.Time
	DeliveredAt       *time.Time
	CancelledAt       *time.Time
	RefundedAt        *time.Time
	RefundCents       int64
	AdminNote         string
	ReturnStatus      string
	ReturnReason      string
	ReturnNote        string
	ReturnRequestedAt *time.Time
}

type OrdersOrderEvent struct {
	ID      uuid.UUID
	OrderID uuid.UUID
	At      time.Time
	Kind    string
	Detail  string
	ActorID *uuid.UUID
}

type OrdersOrderItem struct {
	OrderID        uuid.UUID
	ProductID      uuid.UUID
	Name           string
	UnitPriceCents int64
	Quantity       int32
	VariantID      uuid.UUID
	VariantLabel   string
	Sku            string
}

type PaymentPayment struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	UserID      uuid.UUID
	AmountCents int64
	Currency    string
	Provider    string
	ProviderRef string
	Status      string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Method      string
}

type PlatformAuditLog struct {
	ID        uuid.UUID
	At        time.Time
	ActorID   *uuid.UUID
	ActorRole string
	Action    string
	Entity    string
	EntityID  string
	Detail    []byte
	Ip        string
}

type PlatformJob struct {
	ID          uuid.UUID
	Kind        string
	Payload     []byte
	Status      string
	Attempts    int32
	MaxAttempts int32
	RunAt       time.Time
	LockedUntil *time.Time
	LastError   pgtype.Text
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PromotionCoupon struct {
	ID               uuid.UUID
	Code             string
	Kind             string
	Value            int64
	MinSubtotalCents int64
	StartsAt         *time.Time
	EndsAt           *time.Time
	MaxUses          *int32
	MaxUsesPerUser   *int32
	Active           bool
	CreatedAt        time.Time
}

type PromotionRedemption struct {
	ID            uuid.UUID
	CouponID      uuid.UUID
	OrderID       uuid.UUID
	UserID        uuid.UUID
	DiscountCents int64
	CreatedAt     time.Time
}

type ReviewReview struct {
	ID        uuid.UUID
	ProductID uuid.UUID
	UserID    uuid.UUID
	Rating    int16
	Title     string
	Body      string
	Author    string
	Status    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ShippingMethod struct {
	ID            uuid.UUID
	Name          string
	Description   string
	PriceCents    int64
	FreeOverCents *int64
	MinDays       int32
	MaxDays       int32
	Active        bool
	Position      int32
	CreatedAt     time.Time
}

type WishlistItem struct {
	UserID    uuid.UUID
	ProductID uuid.UUID
	CreatedAt time.Time
}
