// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const archiveProduct = `-- name: ArchiveProduct :execrows
UPDATE catalog.products
SET active = false, archived_at = now(),
    slug = slug || '-archived-' || substr(replace(id::text, '-', ''), 25, 8)
WHERE id = $1 AND archived_at IS NULL
`

// Hides the product everywhere and frees its slug for reuse.
func (q *Queries) ArchiveProduct(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, archiveProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM catalog.categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, category_id, slug, name, description, price_cents, currency, image_url, active, created_at, archived_at, option_name FROM catalog.products WHERE id = $1
`

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (CatalogProduct, error) {
	row := q.db.QueryRow(ctx, getProductByID, id)
	var i CatalogProduct
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.ImageUrl,
		&i.Active,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.OptionName,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT id, category_id, slug, name, description, price_cents, currency, image_url, active, created_at, archived_at, option_name FROM catalog.products WHERE slug = $1 AND archived_at IS NULL
`

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (CatalogProduct, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i CatalogProduct
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Currency,
		&i.ImageUrl,
		&i.Active,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.OptionName,
	)
	return i, err
}

const getProductsByIDs = `-- name: GetProductsByIDs :many
SELECT id, category_id, slug, name, description, price_cents, currency, image_url, active, created_at, archived_at, option_name FROM catalog.products WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetProductsByIDs(ctx context.Context, ids []uuid.UUID) ([]CatalogProduct, error) {
	rows, err := q.db.Query(ctx, getProductsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogProduct
	for rows.Next() {
		var i CatalogProduct
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.ImageUrl,
			&i.Active,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.OptionName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVariant = `-- name: GetVariant :one
SELECT id, product_id, sku, label, price_cents, position, active, created_at FROM catalog.variants WHERE id = $1
`

func (q *Queries) GetVariant(ctx context.Context, id uuid.UUID) (CatalogVariant, error) {
	row := q.db.QueryRow(ctx, getVariant, id)
	var i CatalogVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Label,
		&i.PriceCents,
		&i.Position,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getVariantInfos = `-- name: GetVariantInfos :many
SELECT v.id AS variant_id, v.product_id, v.sku, v.label,
       COALESCE(v.price_cents, p.price_cents)::bigint AS price_cents,
       p.name AS product_name, p.slug AS product_slug, p.image_url, p.currency,
       (COALESCE(v.active AND p.active AND p.archived_at IS NULL, false))::boolean AS active
FROM catalog.variants v
JOIN catalog.products p ON p.id = v.product_id
WHERE v.id = ANY($1::uuid[])
`

type GetVariantInfosRow struct {
	VariantID   uuid.UUID
	ProductID   uuid.UUID
	Sku         string
	Label       string
	PriceCents  int64
	ProductName string
	ProductSlug string
	ImageUrl    string
	Currency    string
	Active      bool
}

// A variant joined with its product: what carts, checkout and orders need.
func (q *Queries) GetVariantInfos(ctx context.Context, ids []uuid.UUID) ([]GetVariantInfosRow, error) {
	rows, err := q.db.Query(ctx, getVariantInfos, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVariantInfosRow
	for rows.Next() {
		var i GetVariantInfosRow
		if err := rows.Scan(
			&i.VariantID,
			&i.ProductID,
			&i.Sku,
			&i.Label,
			&i.PriceCents,
			&i.ProductName,
			&i.ProductSlug,
			&i.ImageUrl,
			&i.Currency,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertCategory = `-- name: InsertCategory :exec
INSERT INTO catalog.categories (id, slug, name) VALUES ($1, $2, $3)
`

type InsertCategoryParams struct {
	ID   uuid.UUID
	Slug string
	Name string
}

func (q *Queries) InsertCategory(ctx context.Context, arg InsertCategoryParams) error {
	_, err := q.db.Exec(ctx, insertCategory, arg.ID, arg.Slug, arg.Name)
	return err
}

const insertProduct = `-- name: InsertProduct :exec
INSERT INTO catalog.products (id, category_id, slug, name, description, price_cents, currency, image_url, active, option_name)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertProductParams struct {
	ID          uuid.UUID
	CategoryID  *uuid.UUID
	Slug        string
	Name        string
	Description string
	PriceCents  int64
	Currency    string
	ImageUrl    string
	Active      bool
	OptionName  string
}

func (q *Queries) InsertProduct(ctx context.Context, arg InsertProductParams) error {
	_, err := q.db.Exec(ctx, insertProduct,
		arg.ID,
		arg.CategoryID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Currency,
		arg.ImageUrl,
		arg.Active,
		arg.OptionName,
	)
	return err
}

const insertVariant = `-- name: InsertVariant :exec
INSERT INTO catalog.variants (id, product_id, sku, label, price_cents, position, active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertVariantParams struct {
	ID         uuid.UUID
	ProductID  uuid.UUID
	Sku        string
	Label      string
	PriceCents *int64
	Position   int32
	Active     bool
}

func (q *Queries) InsertVariant(ctx context.Context, arg InsertVariantParams) error {
	_, err := q.db.Exec(ctx, insertVariant,
		arg.ID,
		arg.ProductID,
		arg.Sku,
		arg.Label,
		arg.PriceCents,
		arg.Position,
		arg.Active,
	)
	return err
}

const listActiveCategories = `-- name: ListActiveCategories :many
SELECT c.id, c.slug, c.name FROM catalog.categories c
WHERE EXISTS (SELECT 1 FROM catalog.products p WHERE p.category_id = c.id AND p.active AND p.archived_at IS NULL)
ORDER BY c.name
`

// Only categories a shopper can actually find something in.
func (q *Queries) ListActiveCategories(ctx context.Context) ([]CatalogCategory, error) {
	rows, err := q.db.Query(ctx, listActiveCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogCategory
	for rows.Next() {
		var i CatalogCategory
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategories = `-- name: ListCategories :many
SELECT id, slug, name FROM catalog.categories ORDER BY name
`

func (q *Queries) ListCategories(ctx context.Context) ([]CatalogCategory, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogCategory
	for rows.Next() {
		var i CatalogCategory
		if err := rows.Scan(&i.ID, &i.Slug, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoryStats = `-- name: ListCategoryStats :many
SELECT c.id, c.slug, c.name, count(p.id)::bigint AS product_count
FROM catalog.categories c
LEFT JOIN catalog.products p ON p.category_id = c.id AND p.archived_at IS NULL
GROUP BY c.id
ORDER BY c.name
`

type ListCategoryStatsRow struct {
	ID           uuid.UUID
	Slug         string
	Name         string
	ProductCount int64
}

func (q *Queries) ListCategoryStats(ctx context.Context) ([]ListCategoryStatsRow, error) {
	rows, err := q.db.Query(ctx, listCategoryStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoryStatsRow
	for rows.Next() {
		var i ListCategoryStatsRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.ProductCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.category_id, p.slug, p.name, p.description, p.price_cents, p.currency,
       p.image_url, p.active, p.created_at, p.archived_at, p.option_name,
       COALESCE((SELECT min(COALESCE(v.price_cents, p.price_cents)) FROM catalog.variants v WHERE v.product_id = p.id AND v.active), p.price_cents)::bigint AS min_price,
       COALESCE((SELECT max(COALESCE(v.price_cents, p.price_cents)) FROM catalog.variants v WHERE v.product_id = p.id AND v.active), p.price_cents)::bigint AS max_price,
       (count(*) OVER ())::bigint AS total
FROM catalog.products p
LEFT JOIN catalog.categories c ON c.id = p.category_id
WHERE (p.archived_at IS NOT NULL) = $1::bool
  AND ($2::bool OR p.active)
  AND ($3::text = ''
       OR to_tsvector('english', p.name || ' ' || p.description) @@ websearch_to_tsquery('english', $3::text)
       OR p.name ILIKE $4::text)
  AND ($5::text = '' OR c.slug = $5::text)
ORDER BY
  CASE WHEN $3::text <> ''
       THEN ts_rank(to_tsvector('english', p.name || ' ' || p.description), websearch_to_tsquery('english', $3::text))
  END DESC NULLS LAST,
  p.created_at DESC, p.id DESC
LIMIT $7 OFFSET $6
`

type ListProductsParams struct {
	Archived        bool
	IncludeInactive bool
	Query           string
	LikePattern     string
	CategorySlug    string
	PageOffset      int32
	PageLimit       int32
}

type ListProductsRow struct {
	ID          uuid.UUID
	CategoryID  *uuid.UUID
	Slug        string
	Name        string
	Description string
	PriceCents  int64
	Currency    string
	ImageUrl    string
	Active      bool
	CreatedAt   time.Time
	ArchivedAt  *time.Time
	OptionName  string
	MinPrice    int64
	MaxPrice    int64
	Total       int64
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.Archived,
		arg.IncludeInactive,
		arg.Query,
		arg.LikePattern,
		arg.CategorySlug,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.Currency,
			&i.ImageUrl,
			&i.Active,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.OptionName,
			&i.MinPrice,
			&i.MaxPrice,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProducts = `-- name: ListVariantsByProducts :many
SELECT id, product_id, sku, label, price_cents, position, active, created_at FROM catalog.variants WHERE product_id = ANY($1::uuid[]) ORDER BY product_id, position, created_at
`

func (q *Queries) ListVariantsByProducts(ctx context.Context, ids []uuid.UUID) ([]CatalogVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProducts, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CatalogVariant
	for rows.Next() {
		var i CatalogVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Label,
			&i.PriceCents,
			&i.Position,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCategory = `-- name: RenameCategory :execrows
UPDATE catalog.categories SET name = $2 WHERE id = $1
`

type RenameCategoryParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) RenameCategory(ctx context.Context, arg RenameCategoryParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameCategory, arg.ID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameVariantLabel = `-- name: RenameVariantLabel :exec
UPDATE catalog.variants SET label = $2 WHERE id = $1
`

type RenameVariantLabelParams struct {
	ID    uuid.UUID
	Label string
}

func (q *Queries) RenameVariantLabel(ctx context.Context, arg RenameVariantLabelParams) error {
	_, err := q.db.Exec(ctx, renameVariantLabel, arg.ID, arg.Label)
	return err
}

const restoreProduct = `-- name: RestoreProduct :execrows
UPDATE catalog.products SET archived_at = NULL WHERE id = $1 AND archived_at IS NOT NULL
`

// Brings the product back as hidden; the admin decides when to publish it.
func (q *Queries) RestoreProduct(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreProduct, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProduct = `-- name: UpdateProduct :execrows
UPDATE catalog.products
SET category_id = $2, slug = $3, name = $4, description = $5, price_cents = $6, image_url = $7, active = $8, option_name = $9
WHERE id = $1 AND archived_at IS NULL
`

type UpdateProductParams struct {
	ID          uuid.UUID
	CategoryID  *uuid.UUID
	Slug        string
	Name        string
	Description string
	PriceCents  int64
	ImageUrl    string
	Active      bool
	OptionName  string
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateProduct,
		arg.ID,
		arg.CategoryID,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.ImageUrl,
		arg.Active,
		arg.OptionName,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVariant = `-- name: UpdateVariant :execrows
UPDATE catalog.variants SET sku = $2, label = $3, price_cents = $4, active = $5 WHERE id = $1
`

type UpdateVariantParams struct {
	ID         uuid.UUID
	Sku        string
	Label      string
	PriceCents *int64
	Active     bool
}

func (q *Queries) UpdateVariant(ctx context.Context, arg UpdateVariantParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateVariant,
		arg.ID,
		arg.Sku,
		arg.Label,
		arg.PriceCents,
		arg.Active,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
