// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearDefaultAddress = `-- name: ClearDefaultAddress :exec
UPDATE identity.addresses SET is_default = false WHERE user_id = $1
`

func (q *Queries) ClearDefaultAddress(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultAddress, userID)
	return err
}

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE identity.refresh_tokens SET revoked_at = now(), rotated_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at, rotated_at
`

func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash []byte) (IdentityRefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, tokenHash)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO identity.users (id, email, password_hash, name, role)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
	)
	return err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM identity.addresses WHERE id = $1 AND user_id = $2
`

type DeleteAddressParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.Exec(ctx, deleteAddress, arg.ID, arg.UserID)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at, rotated_at FROM identity.refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (IdentityRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, created_at FROM identity.users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, created_at FROM identity.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const insertAddress = `-- name: InsertAddress :exec
INSERT INTO identity.addresses (id, user_id, full_name, phone, line1, line2, city, postal_code, country, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAddressParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	FullName   string
	Phone      string
	Line1      string
	Line2      string
	City       string
	PostalCode string
	Country    string
	IsDefault  bool
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) error {
	_, err := q.db.Exec(ctx, insertAddress,
		arg.ID,
		arg.UserID,
		arg.FullName,
		arg.Phone,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.PostalCode,
		arg.Country,
		arg.IsDefault,
	)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO identity.refresh_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, user_id, full_name, phone, line1, line2, city, postal_code, country, is_default, created_at FROM identity.addresses WHERE user_id = $1 ORDER BY is_default DESC, created_at
`

func (q *Queries) ListAddresses(ctx context.Context, userID uuid.UUID) ([]IdentityAddress, error) {
	rows, err := q.db.Query(ctx, listAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityAddress
	for rows.Next() {
		var i IdentityAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.Phone,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.PostalCode,
			&i.Country,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeRefreshTokens = `-- name: PurgeRefreshTokens :execrows
DELETE FROM identity.refresh_tokens
WHERE expires_at < $1 OR (revoked_at IS NOT NULL AND revoked_at < $1)
`

// Expired or revoked tokens have no further use; rotated ones are kept a week for replay (theft) detection.
func (q *Queries) PurgeRefreshTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeRefreshTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllRefreshTokens = `-- name: RevokeAllRefreshTokens :exec
UPDATE identity.refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE identity.refresh_tokens SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
