// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const clearDefaultAddress = `-- name: ClearDefaultAddress :exec
UPDATE identity.addresses SET is_default = false WHERE user_id = $1
`

func (q *Queries) ClearDefaultAddress(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultAddress, userID)
	return err
}

const consumeActionToken = `-- name: ConsumeActionToken :one
UPDATE identity.action_tokens SET used_at = now()
WHERE token_hash = $1 AND kind = $2 AND used_at IS NULL AND expires_at > now()
RETURNING id, user_id, kind, token_hash, expires_at, used_at, created_at
`

type ConsumeActionTokenParams struct {
	TokenHash []byte
	Kind      string
}

func (q *Queries) ConsumeActionToken(ctx context.Context, arg ConsumeActionTokenParams) (IdentityActionToken, error) {
	row := q.db.QueryRow(ctx, consumeActionToken, arg.TokenHash, arg.Kind)
	var i IdentityActionToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Kind,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const consumeRefreshToken = `-- name: ConsumeRefreshToken :one
UPDATE identity.refresh_tokens SET revoked_at = now(), rotated_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now()
RETURNING id, user_id, token_hash, expires_at, revoked_at, created_at, rotated_at
`

func (q *Queries) ConsumeRefreshToken(ctx context.Context, tokenHash []byte) (IdentityRefreshToken, error) {
	row := q.db.QueryRow(ctx, consumeRefreshToken, tokenHash)
	var i IdentityRefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RotatedAt,
	)
	return i, err
}

const countActiveAdmins = `-- name: CountActiveAdmins :one
SELECT count(*)::bigint FROM identity.users WHERE role = 'admin' AND disabled_at IS NULL
`

func (q *Queries) CountActiveAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveAdmins)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO identity.users (id, email, password_hash, name, role, guest, email_verified_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateUserParams struct {
	ID              uuid.UUID
	Email           string
	PasswordHash    string
	Name            string
	Role            string
	Guest           bool
	EmailVerifiedAt *time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
		arg.Role,
		arg.Guest,
		arg.EmailVerifiedAt,
	)
	return err
}

const deleteAddress = `-- name: DeleteAddress :exec
DELETE FROM identity.addresses WHERE id = $1 AND user_id = $2
`

type DeleteAddressParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAddress(ctx context.Context, arg DeleteAddressParams) error {
	_, err := q.db.Exec(ctx, deleteAddress, arg.ID, arg.UserID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM identity.users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, revoked_at, created_at, rotated_at,
       (expires_at <= now())::boolean AS expired,
       COALESCE(EXTRACT(EPOCH FROM (now() - rotated_at)), -1)::float8 AS rotated_age_secs -- -1: never rotated
FROM identity.refresh_tokens WHERE token_hash = $1
`

type GetRefreshTokenByHashRow struct {
	ID             uuid.UUID
	UserID         uuid.UUID
	TokenHash      []byte
	ExpiresAt      time.Time
	RevokedAt      *time.Time
	CreatedAt      time.Time
	RotatedAt      *time.Time
	Expired        bool
	RotatedAgeSecs float64
}

// Ages are computed here, with the database's own clock, so the reuse-detection grace window
// never depends on the app and the database agreeing about the time.
func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash []byte) (GetRefreshTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i GetRefreshTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.Expired,
		&i.RotatedAgeSecs,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, role, created_at, email_verified_at, guest, disabled_at, cart_reminders FROM identity.users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, lower string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, lower)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.EmailVerifiedAt,
		&i.Guest,
		&i.DisabledAt,
		&i.CartReminders,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, role, created_at, email_verified_at, guest, disabled_at, cart_reminders FROM identity.users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.EmailVerifiedAt,
		&i.Guest,
		&i.DisabledAt,
		&i.CartReminders,
	)
	return i, err
}

const insertActionToken = `-- name: InsertActionToken :exec
INSERT INTO identity.action_tokens (id, user_id, kind, token_hash, expires_at) VALUES ($1, $2, $3, $4, $5)
`

type InsertActionTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Kind      string
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertActionToken(ctx context.Context, arg InsertActionTokenParams) error {
	_, err := q.db.Exec(ctx, insertActionToken,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const insertAddress = `-- name: InsertAddress :exec
INSERT INTO identity.addresses (id, user_id, full_name, phone, line1, line2, city, postal_code, country, is_default)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAddressParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	FullName   string
	Phone      string
	Line1      string
	Line2      string
	City       string
	PostalCode string
	Country    string
	IsDefault  bool
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) error {
	_, err := q.db.Exec(ctx, insertAddress,
		arg.ID,
		arg.UserID,
		arg.FullName,
		arg.Phone,
		arg.Line1,
		arg.Line2,
		arg.City,
		arg.PostalCode,
		arg.Country,
		arg.IsDefault,
	)
	return err
}

const insertRefreshToken = `-- name: InsertRefreshToken :exec
INSERT INTO identity.refresh_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type InsertRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, insertRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const invalidateActionTokens = `-- name: InvalidateActionTokens :exec
UPDATE identity.action_tokens SET used_at = now() WHERE user_id = $1 AND kind = $2 AND used_at IS NULL
`

type InvalidateActionTokensParams struct {
	UserID uuid.UUID
	Kind   string
}

func (q *Queries) InvalidateActionTokens(ctx context.Context, arg InvalidateActionTokensParams) error {
	_, err := q.db.Exec(ctx, invalidateActionTokens, arg.UserID, arg.Kind)
	return err
}

const listAddresses = `-- name: ListAddresses :many
SELECT id, user_id, full_name, phone, line1, line2, city, postal_code, country, is_default, created_at FROM identity.addresses WHERE user_id = $1 ORDER BY is_default DESC, created_at
`

func (q *Queries) ListAddresses(ctx context.Context, userID uuid.UUID) ([]IdentityAddress, error) {
	rows, err := q.db.Query(ctx, listAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityAddress
	for rows.Next() {
		var i IdentityAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FullName,
			&i.Phone,
			&i.Line1,
			&i.Line2,
			&i.City,
			&i.PostalCode,
			&i.Country,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, name, role, created_at, email_verified_at, guest, disabled_at, cart_reminders FROM identity.users
WHERE ($1::text = '' OR email ILIKE $2::text OR name ILIKE $2::text)
  AND ($3::text = '' OR role = $3::text)
ORDER BY created_at DESC, id DESC
LIMIT $5 OFFSET $4
`

type ListUsersParams struct {
	Query       string
	LikePattern string
	Role        string
	PageOffset  int32
	PageLimit   int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]IdentityUser, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Query,
		arg.LikePattern,
		arg.Role,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IdentityUser
	for rows.Next() {
		var i IdentityUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.EmailVerifiedAt,
			&i.Guest,
			&i.DisabledAt,
			&i.CartReminders,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE identity.users SET email_verified_at = COALESCE(email_verified_at, now()) WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const purgeActionTokens = `-- name: PurgeActionTokens :execrows
DELETE FROM identity.action_tokens WHERE expires_at < $1 OR (used_at IS NOT NULL AND used_at < $1)
`

func (q *Queries) PurgeActionTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeActionTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeRefreshTokens = `-- name: PurgeRefreshTokens :execrows
DELETE FROM identity.refresh_tokens
WHERE expires_at < $1 OR (revoked_at IS NOT NULL AND revoked_at < $1)
`

// Expired or revoked tokens have no further use; rotated ones are kept a week for replay (theft) detection.
func (q *Queries) PurgeRefreshTokens(ctx context.Context, expiresAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeRefreshTokens, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAllRefreshTokens = `-- name: RevokeAllRefreshTokens :exec
UPDATE identity.refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE identity.refresh_tokens SET revoked_at = now()
WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const setCartReminders = `-- name: SetCartReminders :exec
UPDATE identity.users SET cart_reminders = $2 WHERE id = $1
`

type SetCartRemindersParams struct {
	ID            uuid.UUID
	CartReminders bool
}

func (q *Queries) SetCartReminders(ctx context.Context, arg SetCartRemindersParams) error {
	_, err := q.db.Exec(ctx, setCartReminders, arg.ID, arg.CartReminders)
	return err
}

const setPassword = `-- name: SetPassword :exec
UPDATE identity.users SET password_hash = $2, guest = false WHERE id = $1
`

type SetPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

// Setting a password also proves control of the mailbox it was emailed to (reset) and ends guest status.
func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.Exec(ctx, setPassword, arg.ID, arg.PasswordHash)
	return err
}

const setUserDisabled = `-- name: SetUserDisabled :exec
UPDATE identity.users SET disabled_at = $2 WHERE id = $1
`

type SetUserDisabledParams struct {
	ID         uuid.UUID
	DisabledAt *time.Time
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) error {
	_, err := q.db.Exec(ctx, setUserDisabled, arg.ID, arg.DisabledAt)
	return err
}

const setUserRole = `-- name: SetUserRole :exec
UPDATE identity.users SET role = $2 WHERE id = $1
`

type SetUserRoleParams struct {
	ID   uuid.UUID
	Role string
}

func (q *Queries) SetUserRole(ctx context.Context, arg SetUserRoleParams) error {
	_, err := q.db.Exec(ctx, setUserRole, arg.ID, arg.Role)
	return err
}

const updateUserName = `-- name: UpdateUserName :exec
UPDATE identity.users SET name = $2 WHERE id = $1
`

type UpdateUserNameParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) error {
	_, err := q.db.Exec(ctx, updateUserName, arg.ID, arg.Name)
	return err
}
